---
- hosts: gitlab
  become: true
  vars:
    # Этот плейбук деплоит инфраструктурный сервис GitLab для внутреннего CI/CD в компании «AsmalyshevDevOps».
    gitlab_external_url: "https://gitlab.asmalyshev.ru"
    gitlab_hostname: "gitlab.asmalyshev.ru"
    gitlab_http_bind: 8090
    gitlab_ssh_bind: 2222
    gitlab_shell_ssh_port: 22
    gitlab_image: "gitlab/gitlab-ce:latest"
    gitlab_timezone: "Europe/Moscow"
    gitlab_cpus: "2"
    gitlab_mem_limit: "3g"
    gitlab_mem_reservation: "1g"
    gitlab_root: "/opt/gitlab"
  roles:
    - gitlab
